// E4.S2.T3 (the format) and T4 (the reader)
//
// Every fixture here is built byte by byte, by hand. A file generated by the same code that reads
// it would prove nothing.

#include "Safetensors.h"
#include "Shape.h"
#include "TestSupport.h"
#include "Tensor.h"

#include <bit>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <stdexcept>
#include <string>
#include <vector>

using veda::core::Shape;
using veda::io::read_safetensors;
using veda::io::WeightFile;

namespace
{

std::filesystem::path scratch(const std::string& name)
{
    return std::filesystem::temp_directory_path() / ("veda_safetensors_" + name);
}

void put_u64(std::string& out, uint64_t value)
{
    for (int i = 0; i < 8; ++i)
    {
        out += static_cast<char>((value >> (8 * i)) & 0xFF);
    }
}

void put_f32(std::string& out, float value)
{
    const uint32_t bits = std::bit_cast<uint32_t>(value);
    for (int i = 0; i < 4; ++i)
    {
        out += static_cast<char>((bits >> (8 * i)) & 0xFF);
    }
}

void put_bf16(std::string& out, uint16_t bits)
{
    out += static_cast<char>(bits & 0xFF);
    out += static_cast<char>((bits >> 8) & 0xFF);
}

// header + data, assembled the way the format describes: an 8-byte length, the JSON, then bytes.
std::string build_file(const std::string& header, const std::string& data)
{
    std::string out;
    put_u64(out, header.size());
    out += header;
    out += data;
    return out;
}

std::string write_file(const std::filesystem::path& path, const std::string& contents)
{
    std::ofstream out(path, std::ios::binary);
    out.write(contents.data(), static_cast<std::streamsize>(contents.size()));
    out.close();
    return path.string();
}

std::string message_of(const std::string& path)
{
    try
    {
        (void)read_safetensors(path);
    }
    catch (const std::runtime_error& error)
    {
        return error.what();
    }
    return "";
}

// The two-tensor fixture from the task: an F32 vector and a BF16 matrix.
std::string two_tensor_file()
{
    const std::string header =
        R"({"a":{"dtype":"F32","shape":[2],"data_offsets":[0,8]},)"
        R"("b":{"dtype":"BF16","shape":[2,2],"data_offsets":[8,16]},)"
        R"("__metadata__":{"format":"pt"}})";

    std::string data;
    put_f32(data, 1.0f);
    put_f32(data, 2.0f);
    put_bf16(data, 0x3F80);   // 1.0
    put_bf16(data, 0xC000);   // -2.0
    put_bf16(data, 0x4049);   // 3.140625, pi as bf16 holds it
    put_bf16(data, 0x0000);   // 0.0

    return build_file(header, data);
}

} // namespace

int main()
{
    // --- T3: the layout arithmetic, on the fixture itself ---------------------------------------
    {
        const std::string header =
            R"({"a":{"dtype":"F32","shape":[2],"data_offsets":[0,8]},)"
            R"("b":{"dtype":"BF16","shape":[2,2],"data_offsets":[8,16]},)"
            R"("__metadata__":{"format":"pt"}})";
        const std::string file = two_tensor_file();

        // 8 bytes of length, then the header, then the data
        CHECK_EQ(file.size(), 8 + header.size() + 16);
        CHECK_EQ(static_cast<unsigned char>(file[0]), header.size() & 0xFF);

        // tensor b: shape [2,2] of BF16 is 4 elements of 2 bytes = 8, and the header claims 16-8=8
        CHECK_EQ(size_t{2} * 2 * 2, size_t{8});
        // and its absolute position is 8 + header + its own offset
        CHECK_EQ(8 + header.size() + 8, file.size() - 8);
    }

    // --- T4: a hand-built file reads back exactly -------------------------------------------------
    {
        const auto path = scratch("two.safetensors");
        write_file(path, two_tensor_file());

        const WeightFile weights = read_safetensors(path.string());

        CHECK_EQ(weights.tensor_count(), size_t{2});          // __metadata__ is not a tensor
        CHECK_EQ(weights.names(), std::vector<std::string>({"a", "b"}));   // header order
        CHECK(weights.contains("a"));
        CHECK(!weights.contains("__metadata__"));
        CHECK(!weights.contains("lm_head.weight"));

        const auto& a = weights["a"];
        CHECK_EQ(a.shape(), Shape({2}));
        CHECK_EQ(a.at({0}), 1.0f);
        CHECK_EQ(a.at({1}), 2.0f);
        CHECK(a.is_contiguous());

        // bf16 widened on load: the same values E1.S3.T10 established
        const auto& b = weights["b"];
        CHECK_EQ(b.shape(), Shape({2, 2}));
        CHECK_EQ(b.at({0, 0}), 1.0f);
        CHECK_EQ(b.at({0, 1}), -2.0f);
        CHECK_EQ(b.at({1, 0}), 3.140625f);
        CHECK_EQ(b.at({1, 1}), 0.0f);

        // 8 bytes of F32 plus 8 of BF16 on disk; the BF16 half doubles in memory (AD1)
        CHECK_EQ(weights.bytes_on_disk(), size_t{16});
        CHECK_EQ(weights.bytes_resident(), size_t{24});

        // the tensors are independent values, not views into one buffer
        CHECK(a.storage() != b.storage());

        CHECK_THROWS_AS(weights["nope"], std::runtime_error);
        std::filesystem::remove(path);
    }

    // a file with no tensors at all is legal
    {
        const auto path = scratch("empty.safetensors");
        write_file(path, build_file(R"({"__metadata__":{"format":"pt"}})", ""));
        const WeightFile weights = read_safetensors(path.string());
        CHECK_EQ(weights.tensor_count(), size_t{0});
        CHECK_EQ(weights.bytes_on_disk(), size_t{0});
        CHECK(weights.names().empty());
        std::filesystem::remove(path);

        const auto bare = scratch("bare.safetensors");
        write_file(bare, build_file("{}", ""));
        CHECK_EQ(read_safetensors(bare.string()).tensor_count(), size_t{0});
        std::filesystem::remove(bare);
    }

    // shapes the real file contains, and offsets that need not be in ascending order
    {
        const auto path = scratch("order.safetensors");
        // "second" occupies bytes 0..8, "first" occupies 8..16 — the format does not require order
        const std::string header =
            R"({"first":{"dtype":"F32","shape":[2],"data_offsets":[8,16]},)"
            R"("second":{"dtype":"F32","shape":[2],"data_offsets":[0,8]}})";
        std::string data;
        put_f32(data, 30.0f);
        put_f32(data, 40.0f);
        put_f32(data, 10.0f);
        put_f32(data, 20.0f);
        write_file(path, build_file(header, data));

        const WeightFile weights = read_safetensors(path.string());
        CHECK_EQ(weights["first"].at({0}), 10.0f);
        CHECK_EQ(weights["second"].at({0}), 30.0f);
        CHECK_EQ(weights.names()[0], std::string("first"));   // header order, not byte order
        std::filesystem::remove(path);
    }

    // a rank-0 tensor and a zero-element one
    {
        const auto path = scratch("degenerate.safetensors");
        const std::string header =
            R"({"scalar":{"dtype":"F32","shape":[],"data_offsets":[0,4]},)"
            R"("empty":{"dtype":"BF16","shape":[0,4],"data_offsets":[4,4]}})";
        std::string data;
        put_f32(data, 42.0f);
        write_file(path, build_file(header, data));

        const WeightFile weights = read_safetensors(path.string());
        CHECK_EQ(weights["scalar"].shape().rank(), size_t{0});
        CHECK_EQ(weights["scalar"].at({}), 42.0f);
        CHECK_EQ(weights["empty"].shape(), Shape({0, 4}));
        CHECK_EQ(weights["empty"].numel(), size_t{0});
        std::filesystem::remove(path);
    }

    // --- every check from the format, each turning a potential overrun into a message -------------
    {
        // a file too small to hold a header length
        {
            const auto path = scratch("tiny.safetensors");
            write_file(path, "VEDA");
            CHECK_THROWS_AS(read_safetensors(path.string()), std::runtime_error);
            CHECK(message_of(path.string()).find("too small") != std::string::npos);
            std::filesystem::remove(path);
        }

        // a missing file
        CHECK_THROWS_AS(read_safetensors(scratch("absent.safetensors").string()),
                        std::runtime_error);

        // a header length beyond the file
        {
            const auto path = scratch("longheader.safetensors");
            std::string contents;
            put_u64(contents, 4096);
            contents += R"({"a":{"dtype":"F32","shape":[1],"data_offsets":[0,4]}})";
            write_file(path, contents);
            CHECK(message_of(path.string()).find("header claims 4096") != std::string::npos);
            std::filesystem::remove(path);
        }

        // a header that is not JSON — the parser's own message, with a position
        {
            const auto path = scratch("badjson.safetensors");
            write_file(path, build_file(R"({"a": )", ""));
            const std::string message = message_of(path.string());
            CHECK(message.find("not valid JSON") != std::string::npos);
            CHECK(message.find("line 1") != std::string::npos);
            std::filesystem::remove(path);
        }

        // an unsupported dtype fails loudly and is never reinterpreted
        {
            const auto path = scratch("f16.safetensors");
            write_file(path, build_file(
                                 R"({"a":{"dtype":"F16","shape":[2],"data_offsets":[0,4]}})",
                                 std::string(4, '\0')));
            const std::string message = message_of(path.string());
            CHECK(message.find("F16") != std::string::npos);
            CHECK(message.find("unsupported dtype") != std::string::npos);
            std::filesystem::remove(path);
        }

        // a byte length that disagrees with the shape
        {
            const auto path = scratch("badlength.safetensors");
            write_file(path, build_file(
                                 R"({"a":{"dtype":"BF16","shape":[2,2],"data_offsets":[0,16]}})",
                                 std::string(16, '\0')));
            const std::string message = message_of(path.string());
            CHECK(message.find("claims 16 bytes") != std::string::npos);
            CHECK(message.find("(2, 2)") != std::string::npos);
            CHECK(message.find("needs 8") != std::string::npos);
            std::filesystem::remove(path);
        }

        // a range running past the data section: the header is intact, the file is short.
        // This is the dangerous one — without the check it reads whatever follows in memory.
        {
            const auto path = scratch("truncated.safetensors");
            const std::string full = two_tensor_file();
            write_file(path, full.substr(0, full.size() - 6));
            const std::string message = message_of(path.string());
            CHECK(message.find("past the") != std::string::npos);
            CHECK(message.find("data section") != std::string::npos);
            std::filesystem::remove(path);
        }

        // a descending range
        {
            const auto path = scratch("descending.safetensors");
            write_file(path, build_file(
                                 R"({"a":{"dtype":"F32","shape":[1],"data_offsets":[8,4]}})",
                                 std::string(8, '\0')));
            CHECK(message_of(path.string()).find("ascending") != std::string::npos);
            std::filesystem::remove(path);
        }

        // an entry missing a field
        {
            const auto path = scratch("incomplete.safetensors");
            write_file(path, build_file(R"({"a":{"dtype":"F32","shape":[1]}})", std::string(4, '\0')));
            CHECK(message_of(path.string()).find("missing dtype, shape or data_offsets") !=
                  std::string::npos);
            std::filesystem::remove(path);
        }

        // a negative dimension
        {
            const auto path = scratch("negative.safetensors");
            write_file(path, build_file(
                                 R"({"a":{"dtype":"F32","shape":[-1],"data_offsets":[0,4]}})",
                                 std::string(4, '\0')));
            CHECK(message_of(path.string()).find("negative dimension") != std::string::npos);
            std::filesystem::remove(path);
        }

        // every message names the file
        {
            const auto path = scratch("tiny.safetensors");
            write_file(path, "VEDA");
            CHECK(message_of(path.string()).find("tiny.safetensors") != std::string::npos);
            std::filesystem::remove(path);
        }
    }

    // a file shaped like the real one: several layers' worth of names and plausible shapes
    {
        const auto path = scratch("modelish.safetensors");
        std::string header = "{";
        std::string data;
        size_t offset = 0;
        std::vector<std::string> expected_names;

        for (int layer = 0; layer < 3; ++layer)
        {
            const std::string prefix = "model.layers." + std::to_string(layer) + ".";
            for (const auto& [suffix, rows] :
                 std::vector<std::pair<std::string, size_t>>{{"self_attn.q_proj.weight", 8},
                                                             {"self_attn.k_proj.weight", 4},
                                                             {"input_layernorm.weight", 1}})
            {
                const size_t columns = 8;
                const size_t elements = rows * columns;
                const size_t bytes = elements * 2;
                const std::string name = prefix + suffix;

                if (header.size() > 1)
                {
                    header += ",";
                }
                header += "\"" + name + "\":{\"dtype\":\"BF16\",\"shape\":[" +
                          std::to_string(rows) + "," + std::to_string(columns) +
                          "],\"data_offsets\":[" + std::to_string(offset) + "," +
                          std::to_string(offset + bytes) + "]}";
                for (size_t i = 0; i < elements; ++i)
                {
                    put_bf16(data, 0x3F80);   // every weight is 1.0
                }
                offset += bytes;
                expected_names.push_back(name);
            }
        }
        header += "}";
        write_file(path, build_file(header, data));

        const WeightFile weights = read_safetensors(path.string());
        CHECK_EQ(weights.tensor_count(), size_t{9});
        CHECK_EQ(weights.names(), expected_names);
        CHECK_EQ(weights["model.layers.1.self_attn.q_proj.weight"].shape(), Shape({8, 8}));
        CHECK_EQ(weights["model.layers.2.self_attn.k_proj.weight"].shape(), Shape({4, 8}));
        CHECK_EQ(weights["model.layers.0.input_layernorm.weight"].at({0, 3}), 1.0f);
        CHECK_EQ(weights.bytes_on_disk() * 2, weights.bytes_resident());   // bf16 doubles
        std::filesystem::remove(path);
    }

    return VEDA_TEST_SUMMARY("SafetensorsTest");
}
